# Generated by Django 6.0.2 on 2026-02-26 08:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='movie_genre_title_a81d40_idx')],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=4000, null=True)),
                ('poster', models.ImageField(upload_to='movies/posters')),
                ('genres', models.ManyToManyField(related_name='movies', to='movie.genre')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['title'], name='movie_movie_title_0a2a49_idx'), models.Index(fields=['-created_at'], name='movie_movie_created_aa5d0b_idx')],
            },
        ),
    ]
